// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ZbUhZAqNewvne1hrLFGwKgfi-Crhr7c',
    appId: '1:717760620776:web:71069260368337f5da415d',
    messagingSenderId: '717760620776',
    projectId: 'mrtouride',
    authDomain: 'mrtouride.firebaseapp.com',
    storageBucket: 'mrtouride.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3sb16eZYsEbnROBMWkJmTUxEOSr-XZ98',
    appId: '1:717760620776:android:c3b0ae90bb3acc9fda415d',
    messagingSenderId: '717760620776',
    projectId: 'mrtouride',
    storageBucket: 'mrtouride.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjmRFU80i1J_-AYcmgBFAXvkh4djw6KNQ',
    appId: '1:717760620776:ios:62eb69526ebcb493da415d',
    messagingSenderId: '717760620776',
    projectId: 'mrtouride',
    storageBucket: 'mrtouride.appspot.com',
    iosClientId: '717760620776-u9qrml7csen58s00k1b1d1bni9lj0b20.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrtouride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjmRFU80i1J_-AYcmgBFAXvkh4djw6KNQ',
    appId: '1:717760620776:ios:62eb69526ebcb493da415d',
    messagingSenderId: '717760620776',
    projectId: 'mrtouride',
    storageBucket: 'mrtouride.appspot.com',
    iosClientId: '717760620776-u9qrml7csen58s00k1b1d1bni9lj0b20.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrtouride',
  );
}
